# define prune ratios for your network
# 66.66 / 75.99 (filter sparsity / weight sparsity)
prune_ratios:
   features.0.weight:
     0.80
   features.3.weight:
     0.80
   features.7.weight:
     0.80
   features.10.weight:
     0.80
   features.14.weight:
     0.80
   features.17.weight:
     0.80
   features.20.weight:
     0.80
   features.24.weight:
     0.80
   features.27.weight:
     0.80
   features.30.weight:
     0.80
   features.34.weight:
     0.80
   features.37.weight:
     0.80
   features.40.weight:
     0.80